name: CI - Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run basic test
        run: |
          echo "Comprobando que index.html existe..."
          test -f index.html && echo "✔️ Todo correcto"
